[MVP] GraFx/Actions Helper Functions
chili-publish/grafx-documentation pull request #224
Opened 2023-10-18 16:20 UTC by BramVerniest

2023-10-20 13:24 UTC, jeroencosyn requested changes

2023-10-23 08:42 UTC, BramVerniest commented on docs/GraFx-Studio/concepts/helper-functions/index.md
> +Start typing one of the 4 type of functions (see below) and the Action Editor will suggest the list of available functions.
On it

2023-10-23 09:17 UTC, BramVerniest commented on docs/GraFx-Studio/concepts/helper-functions/index.md
> +Start typing one of the 4 type of functions (see below) and the Action Editor will suggest the list of available functions.
New additions, adding more ways to find helper functions

2023-10-23 09:51 UTC, jeroencosyn approved these changes

2023-10-23 13:06 UTC, merged