[GraFx Studio] Autogrow
chili-publish/grafx-documentation pull request #427
Opened 2024-11-04 20:53 UTC by BramVerniest

2024-11-12 20:50 UTC, jeroencosyn requested changes

2024-11-12 20:50 UTC, jeroencosyn commented on docs/GraFx-Studio/guides/text-frame/errorhandling.png
The "Fail output" dropdown menu is not available yet.

2024-11-12 20:50 UTC, jeroencosyn commented on docs/GraFx-Studio/guides/text-frame/index.md
> +See also [Output Settings](/GraFx-Studio/guides/output/settings/) to define how a VDP job should handle text overflow.
You can only configure "Continue batch output after failure" for now. Text overflow is a failure.

2024-11-12 20:50 UTC, jeroencosyn commented on docs/GraFx-Studio/guides/text-frame/index.md
> +Select the text frame and enable "Copyfitting" to adjust font size to fit the frame by allowing slight reduction or growth.
Not only a slight reduction or growth. That depends on your min/max settings.

2024-11-12 20:50 UTC, jeroencosyn commented on docs/GraFx-Studio/guides/text-frame/index.md
> +Enable "Autogrow" to allow the frame to expand as needed to fit content of varying lengths. For instance, records in a dataset might contain differing character counts.
Expand or shrink is also possible.

2024-11-12 20:50 UTC, jeroencosyn commented on docs/GraFx-Studio/guides/text-frame/index.md
> +> Note: When Copyfitting is enabled, Autogrow is disabled.
I would also mention this for auto-grow. When that is enabled, copyfitting is disabled. They cannot be enabled together.

2024-11-12 20:50 UTC, jeroencosyn commented on docs/GraFx-Studio/guides/text-frame/index.md
> +To enable Autogrow, select at least one growth direction, or uncheck "Autogrow" to disable it.
To enable it you have to use the toggle. The component with the arrows is only visible when it's enabled, so you cannot use it to enable it.

2024-11-12 20:50 UTC, jeroencosyn commented on docs/GraFx-Studio/guides/text-frame/index.md
> +#### Auto-grow
Maybe also good to mention that auto-grow cannot be used when the frame is rotated. When the rotation is different from 0º, auto-grow cannot be enabled. Or when auto-grow is enabled, the frame cannot be rotated anymore.

2024-11-21 14:13 UTC, closed without merging

2024-11-21 14:14 UTC, BramVerniest commented
Will re-open. Need PR slot